<a href="https://colab.research.google.com/github/Prashantlondhe123/ML-Project/blob/main/genetic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Project : Iris Flower Analysis

In [ ]:
pip install sklearn-genetic

     |████████████████████████████████| 160 kB 5.0 MB/s 


In [ ]:
import random
import numpy as np
from sklearn import datasets, linear_model
from genetic_selection import GeneticSelectionCV

# When using multiple processes (n_jobs != 1), protect the entry point of the program if necessary
if __name__ == "__main__":

    # Set seed for reproducibility
    random.seed(42)
    np.random.seed(42)

    iris = datasets.load_iris()

    # Some noisy data not correlated
    E = np.random.uniform(0, 0.1, size=(len(iris.data), 20))

    X = np.hstack((iris.data, E))
    y = iris.target

    estimator = linear_model.LogisticRegression(solver="liblinear", multi_class="ovr")

    selector = GeneticSelectionCV(
        estimator,
        cv=5,
        verbose=1,
        scoring="accuracy",
        max_features=5,
        n_population=50,
        crossover_proba=0.5,
        mutation_proba=0.2,
        n_generations=40,
        crossover_independent_proba=0.5,
        mutation_independent_proba=0.05,
        tournament_size=3,
        n_gen_no_change=10,
        caching=True,
        n_jobs=-1,
    )
    model = selector.fit(X, y)



Selecting features with genetic algorithm.
gen	nevals	avg                            	std                            	min                            	max                            
0  	50    	[ 0.515067  2.9       0.054454]	[ 0.216365  1.345362  0.022473]	[ 0.206667  1.        0.021082]	[ 0.873333  5.        0.13433 ]
1  	25    	[ 0.677733  3.3       0.046691]	[ 0.183112  1.236932  0.01615 ]	[ 0.313333  1.        0.01633 ]	[ 0.893333  5.        0.080554]
2  	32    	[-1199.323333     3.7       1200.042246]	[ 3249.865241     1.360147  3249.599761]	[-10000.            1.            0.026667]	[     0.92      7.    10000.  ]
3  	25    	[-599.2         3.7       600.049747]   	[ 2375.070535     1.153256  2374.855849]	[-10000.            1.            0.026667]	[     0.933333      7.        10000.      ]
4  	31    	[-399.144       3.76      400.051589]   	[ 1959.766525     0.991161  1959.581264]	[-10000.            1.            0.026667]	[     0.933333      6.        10000.      ]
5  	29   

In [ ]:
model.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
model.score(X,y)

0.96

In [ ]:
X[0]

array([5.10000000e+00, 3.50000000e+00, 1.40000000e+00, 2.00000000e-01,
       3.74540119e-02, 9.50714306e-02, 7.31993942e-02, 5.98658484e-02,
       1.56018640e-02, 1.55994520e-02, 5.80836122e-03, 8.66176146e-02,
       6.01115012e-02, 7.08072578e-02, 2.05844943e-03, 9.69909852e-02,
       8.32442641e-02, 2.12339111e-02, 1.81824967e-02, 1.83404510e-02,
       3.04242243e-02, 5.24756432e-02, 4.31945019e-02, 2.91229140e-02])

In [ ]:
model.predict([[5.10000000e+00, 3.50000000e+00, 1.40000000e+00, 2.00000000e-01,
       3.74540119e-02, 9.50714306e-02, 7.31993942e-02, 5.98658484e-02,
       1.56018640e-02, 1.55994520e-02, 5.80836122e-03, 8.66176146e-02,
       6.01115012e-02, 7.08072578e-02, 2.05844943e-03, 9.69909852e-02,
       8.32442641e-02, 2.12339111e-02, 1.81824967e-02, 1.83404510e-02,
       3.04242243e-02, 5.24756432e-02, 4.31945019e-02, 2.91229140e-02]])

array([0])

In [ ]:
import pickle 

In [ ]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

In [ ]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [ ]:
X[140]

array([6.70000000e+00, 3.10000000e+00, 5.60000000e+00, 2.40000000e+00,
       7.92595116e-02, 9.07898794e-02, 9.43701593e-02, 9.60135604e-02,
       5.21459639e-02, 9.77307908e-02, 7.57310207e-02, 1.61671436e-02,
       4.76900106e-02, 7.18331175e-02, 2.47340316e-02, 6.40615184e-02,
       6.66600479e-02, 1.62699744e-02, 5.65085312e-02, 7.71626911e-02,
       4.98895665e-02, 1.21031168e-03, 9.03846908e-04, 3.57029344e-02])

In [ ]:
mp.predict([[6.70000000e+00, 3.10000000e+00, 5.60000000e+00, 2.40000000e+00,
       7.92595116e-02, 9.07898794e-02, 9.43701593e-02, 9.60135604e-02,
       5.21459639e-02, 9.77307908e-02, 7.57310207e-02, 1.61671436e-02,
       4.76900106e-02, 7.18331175e-02, 2.47340316e-02, 6.40615184e-02,
       6.66600479e-02, 1.62699744e-02, 5.65085312e-02, 7.71626911e-02,
       4.98895665e-02, 1.21031168e-03, 9.03846908e-04, 3.57029344e-02]])


array([2])