<a href="https://colab.research.google.com/github/Prashantlondhe123/ML-Project/blob/main/Hand_Written_Digit_Recognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Project: Hand Written Digit Recognition using Genetic Algorithm

In [ ]:
pip install sklearn-genetic

     |████████████████████████████████| 160 kB 9.6 MB/s 


In [ ]:
import random
import numpy as np
from sklearn import datasets, linear_model
from genetic_selection import GeneticSelectionCV

# When using multiple processes (n_jobs != 1), protect the entry point of the program if necessary
if __name__ == "__main__":

    # Set seed for reproducibility
    random.seed(42)
    np.random.seed(42)

    digit = datasets.load_digits()

    # Some noisy data not correlated
    E = np.random.uniform(0, 0.1, size=(len(digit.data), 20))

    X = np.hstack((digit.data, E))
    y = digit.target

    estimator = linear_model.LogisticRegression(solver="liblinear", multi_class="ovr")

    selector = GeneticSelectionCV(
        estimator,
        cv=5,
        verbose=1,
        scoring="accuracy",
        max_features=5,
        n_population=50,
        crossover_proba=0.5,
        mutation_proba=0.2,
        n_generations=40,
        crossover_independent_proba=0.5,
        mutation_independent_proba=0.05,
        tournament_size=3,
        n_gen_no_change=10,
        caching=True,
        n_jobs=-1,
    )
    model = selector.fit(X, y)

Selecting features with genetic algorithm.
gen	nevals	avg                            	std                            	min                            	max                            
0  	50    	[ 0.271553  3.32      0.02096 ]	[ 0.114249  1.362938  0.01172 ]	[ 0.086252  1.        0.001459]	[ 0.525887  5.        0.056455]
1  	34    	[-1399.702122     4.52      1400.022738]	[ 3469.990501     2.247132  3469.861141]	[-10000.           1.           0.00855]	[     0.525887     15.        10000.      ]
2  	33    	[-1999.700685     4.8       2000.022232]	[ 4000.149658     1.969772  3999.988884]	[-10000.            1.            0.004772]	[     0.525887     11.        10000.      ]
3  	28    	[-2199.660901     5.08      2200.022269]	[ 4142.643126     1.998399  4142.451209]	[-10000.            1.            0.008381]	[     0.56706     12.       10000.     ]   
4  	33    	[-2799.665644     5.08      2800.016618]	[ 4490.197372     1.916664  4489.978501]	[-10000.            2.            0.009583]	[ 

In [ ]:
model.predict(X)

array([0, 1, 6, ..., 8, 3, 6])

In [ ]:
X[1]

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.20000000e+01,
       1.30000000e+01, 5.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.10000000e+01,
       1.60000000e+01, 9.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 3.00000000e+00, 1.50000000e+01,
       1.60000000e+01, 6.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 7.00000000e+00, 1.50000000e+01, 1.60000000e+01,
       1.60000000e+01, 2.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.60000000e+01,
       1.60000000e+01, 3.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.60000000e+01,
       1.60000000e+01, 6.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.60000000e+01,
       1.60000000e+01, 6.00000000e+00, 0.00000000e+00, 0.00000000e+00,
      

In [ ]:
model.predict([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.20000000e+01,
       1.30000000e+01, 5.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.10000000e+01,
       1.60000000e+01, 9.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 3.00000000e+00, 1.50000000e+01,
       1.60000000e+01, 6.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 7.00000000e+00, 1.50000000e+01, 1.60000000e+01,
       1.60000000e+01, 2.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.60000000e+01,
       1.60000000e+01, 3.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.60000000e+01,
       1.60000000e+01, 6.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.60000000e+01,
       1.60000000e+01, 6.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.10000000e+01,
       1.60000000e+01, 1.00000000e+01, 0.00000000e+00, 0.00000000e+00,
       6.11852895e-02, 1.39493861e-02, 2.92144649e-02, 3.66361843e-02,
       4.56069984e-02, 7.85175961e-02, 1.99673782e-02, 5.14234438e-02,
       5.92414569e-02, 4.64504127e-03, 6.07544852e-02, 1.70524124e-02,
       6.50515930e-03, 9.48885537e-02, 9.65632033e-02, 8.08397348e-02,
       3.04613769e-02, 9.76721140e-03, 6.84233027e-02, 4.40152494e-02]])

array([1])